<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ShippingClass;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');


        $products = [

            // ---------------------------------------------------------------
            // LED LIGHT BARS — 6 Modes Series
            // ---------------------------------------------------------------
            [
                'category' => '6-modes-series',
                'brand' => 'Auxbeam',
                'name' => '22 Inch 6 Modes Series 120W Amber & White LED Light Bar',
                'sku' => 'ZD000655',
                'short_description' => '22" straight light bar with 6 switchable color modes — white, amber, and strobe',
                'description' => 'Six switchable lighting modes: white, amber, white+amber, and three strobe variations. Memory function retains the last selected mode on restart. Built with 3030 LED chips for maximum brightness. IP68 waterproof rated. Voltage: 9–32V DC. Operating temperature: -40°C to 85°C. Lifespan: 50,000+ hours. Power: 120W. Lumens: 12,000 LM.',
                'price' => 99.00,
                'compare_price' => 129.00,
                'cost_price' => 52.00,
                'quantity' => 50,
                'weight' => 2.8,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'light-bar',
            ],
            [
                'category' => '6-modes-series',
                'brand' => 'Auxbeam',
                'name' => '30 Inch 6 Modes Series 180W Amber & White LED Light Bar',
                'sku' => 'ZD000654',
                'short_description' => '30" straight light bar with 6 switchable color modes — white, amber, and strobe',
                'description' => 'Six switchable lighting modes: white, amber, white+amber, and three strobe variations. Memory function retains the last selected mode on restart. Built with 3030 LED chips. IP68 waterproof. Voltage: 9–32V DC. Operating temperature: -40°C to 85°C. Lifespan: 50,000+ hours. Power: 180W. Lumens: 18,000 LM.',
                'price' => 129.99,
                'compare_price' => 159.00,
                'cost_price' => 68.00,
                'quantity' => 40,
                'weight' => 3.8,
                'is_featured' => true,
                'is_trending' => false,
                'shipping_class' => 'light-bar',
            ],
            [
                'category' => '6-modes-series',
                'brand' => 'Auxbeam',
                'name' => '42 Inch 6 Modes Series 240W Curved Amber & White LED Light Bar',
                'sku' => 'ZD000653',
                'short_description' => '42" curved light bar with 6 switchable color modes',
                'description' => 'Six switchable lighting modes: white, amber, white+amber, and three strobe variations. Curved design for wider flood coverage. Memory function retains last mode. 3030 LED chips, IP68, 9–32V, -40°C to 85°C, 50,000hr lifespan. Power: 240W. Lumens: 24,000 LM.',
                'price' => 149.99,
                'compare_price' => 189.00,
                'cost_price' => 78.00,
                'quantity' => 30,
                'weight' => 5.2,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'oversized',
            ],
            [
                'category' => '6-modes-series',
                'brand' => 'Auxbeam',
                'name' => '50 Inch 6 Modes Series 288W Curved Amber & White LED Light Bar',
                'sku' => 'ZD000652',
                'short_description' => '50" curved light bar with 6 switchable color modes',
                'description' => 'Six switchable lighting modes: white, amber, white+amber, and three strobe variations. Curved design for wide area coverage. 3030 LED chips, IP68, 9–32V, -40°C to 85°C, 50,000hr lifespan. Power: 288W. Lumens: 28,800 LM.',
                'price' => 169.99,
                'compare_price' => 219.00,
                'cost_price' => 88.00,
                'quantity' => 25,
                'weight' => 6.5,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'oversized',
            ],
            [
                'category' => '6-modes-series',
                'brand' => 'Auxbeam',
                'name' => '3 Inch 6 Modes Series 72W White & Amber LED Light Bar',
                'sku' => 'ZD000650',
                'short_description' => 'Compact 3" light bar with 6 switchable color modes',
                'description' => 'Compact 3-inch LED light bar with six switchable modes including white, amber, white+amber, and strobe variations. Perfect for trucks, ATVs, and UTVs. Power: 72W. IP68 waterproof. Voltage: 9–32V.',
                'price' => 59.99,
                'compare_price' => 79.00,
                'cost_price' => 30.00,
                'quantity' => 80,
                'weight' => 0.8,
                'is_featured' => false,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // LED LIGHT BARS — 5D-PRO Series
            // ---------------------------------------------------------------
            [
                'category' => '5d-pro-series',
                'brand' => 'Auxbeam',
                'name' => '22 Inch 5D-PRO Series 120W LED Light Bar Combo Beam',
                'sku' => 'AB-5DPRO-22',
                'short_description' => '22" 5D-PRO LED light bar with high-intensity combo beam',
                'description' => 'Premium 5D-PRO optical lens design for maximum light output and beam distance. Combo beam pattern combines spot and flood for versatile coverage. Die-cast aluminum housing with IP67 waterproof rating. Power: 120W. Voltage: 9–32V DC. Lifespan: 50,000+ hours. Includes wiring harness.',
                'price' => 119.99,
                'compare_price' => 149.00,
                'cost_price' => 62.00,
                'quantity' => 35,
                'weight' => 3.0,
                'is_featured' => true,
                'is_trending' => false,
                'shipping_class' => 'light-bar',
            ],
            [
                'category' => '5d-pro-series',
                'brand' => 'Auxbeam',
                'name' => '32 Inch 5D-PRO Series 180W LED Light Bar Combo Beam',
                'sku' => 'AB-5DPRO-32',
                'short_description' => '32" 5D-PRO LED light bar with high-intensity combo beam',
                'description' => 'Premium 5D-PRO optical lens for maximum throw and flood coverage. Heavy-duty die-cast aluminum housing. IP67 waterproof. Stainless steel hardware. Power: 180W. Lumens: 18,000 LM. Voltage: 9–32V. Color Temp: 6000K. Includes mounting brackets and wiring harness.',
                'price' => 149.99,
                'compare_price' => 189.00,
                'cost_price' => 78.00,
                'quantity' => 28,
                'weight' => 4.5,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'light-bar',
            ],
            [
                'category' => '5d-pro-series',
                'brand' => 'Auxbeam',
                'name' => '50 Inch 5D-PRO Series 288W LED Light Bar Combo Beam',
                'sku' => 'AB-5DPRO-50',
                'short_description' => '50" 5D-PRO LED light bar — maximum power and range',
                'description' => 'The ultimate 5D-PRO light bar for extreme off-road use. Combo beam pattern. Heavy-duty housing. IP67. Power: 288W. Lumens: 28,800 LM. Voltage: 9–32V. Color Temp: 6000K. Includes mounting hardware and wiring harness.',
                'price' => 199.99,
                'compare_price' => 249.00,
                'cost_price' => 105.00,
                'quantity' => 20,
                'weight' => 6.8,
                'is_featured' => true,
                'is_trending' => false,
                'shipping_class' => 'oversized',
            ],

            // ---------------------------------------------------------------
            // LED LIGHT BARS — RGBW / V-PRO Series
            // ---------------------------------------------------------------
            [
                'category' => 'rgbw-light-bars',
                'brand' => 'Auxbeam',
                'name' => '22 Inch V-PRO Series 120W RGBW Color Changing LED Light Bar',
                'sku' => 'QP008565',
                'short_description' => '22" RGBW light bar with Bluetooth app control and millions of colors',
                'description' => 'V-PRO RGBW LED light bar with full-color RGB lighting plus white work light mode. Bluetooth app control (iOS & Android). Multiple dynamic modes including strobe, fade, chase, and solid color. IP67 waterproof. Power: 120W. Voltage: 9–32V. Perfect for trucks, Jeeps, and off-road vehicles.',
                'price' => 129.99,
                'compare_price' => 169.00,
                'cost_price' => 68.00,
                'quantity' => 45,
                'weight' => 3.2,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'light-bar',
            ],

            // ---------------------------------------------------------------
            // LED HEADLIGHTS — 7 Inch Round (Jeep)
            // ---------------------------------------------------------------
            [
                'category' => 'rgb-halo-headlights',
                'brand' => 'Auxbeam',
                'name' => '7 Inch 80W RGB Flowing Halo LED Headlights for Jeep Wrangler (Pair)',
                'sku' => 'QP004648',
                'short_description' => '7" round LED headlights with RGB flowing halo ring and Bluetooth app control for Jeep Wrangler',
                'description' => 'Set of two 7-inch round LED headlights with 155 dynamic RGB halo ring modes controlled via Bluetooth app. Hi beam: 8,000 LM / 80W. Lo beam: 6,500 LM. Color temperature: 6000K. IP67 waterproof. Fitment: Jeep Wrangler JK (2007–2017), LJ (2004–2006), TJ (1997–2006), CJ-7, CJ-8, Hummer, Land Rover Defender. Package includes 2× headlights, 2× H4-to-H13 adapters, 1× Bluetooth control harness.',
                'price' => 169.99,
                'compare_price' => 199.99,
                'cost_price' => 88.00,
                'quantity' => 40,
                'weight' => 2.5,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'fragile',
            ],
            [
                'category' => '7-inch-round-headlights',
                'brand' => 'Auxbeam',
                'name' => '7 Inch 135W Starlight Flow Series DOT Approved LED Headlights with DRL & Turn Signal (Pair) — Silver',
                'sku' => 'QP010571',
                'short_description' => 'DOT-approved 7" round LED headlights with DRL and integrated turn signal',
                'description' => 'Starlight Flow Series 7-inch round LED headlights. DOT approved for road use. Integrated DRL and sequential turn signal. Silver housing. Hi beam: 135W total (pair). IP67 waterproof. Plug-and-play H4 connector. Fitment: Jeep Wrangler JK/TJ/LJ/CJ, Land Rover Defender, Hummer H1/H2. Sold as a pair.',
                'price' => 185.99,
                'compare_price' => 249.99,
                'cost_price' => 96.00,
                'quantity' => 35,
                'weight' => 2.8,
                'is_featured' => true,
                'is_trending' => false,
                'shipping_class' => 'fragile',
            ],
            [
                'category' => '7-inch-round-headlights',
                'brand' => 'Auxbeam',
                'name' => '7 Inch 135W Starlight Flow Series DOT Approved LED Headlights with DRL & Turn Signal (Pair) — Black',
                'sku' => 'QP010907',
                'short_description' => 'DOT-approved 7" round LED headlights with DRL and integrated turn signal — black housing',
                'description' => 'Starlight Flow Series 7-inch round LED headlights. DOT approved for road use. Integrated DRL and sequential turn signal. Black housing. Hi beam: 135W total (pair). IP67 waterproof. Plug-and-play H4 connector. Fitment: Jeep Wrangler JK/TJ/LJ/CJ, Land Rover Defender, Hummer H1/H2. Sold as a pair.',
                'price' => 199.99,
                'compare_price' => 249.99,
                'cost_price' => 103.00,
                'quantity' => 30,
                'weight' => 2.8,
                'is_featured' => false,
                'is_trending' => true,
                'shipping_class' => 'fragile',
            ],

            // ---------------------------------------------------------------
            // LED OFF ROAD LIGHTS — Pod Lights & Work Lights
            // ---------------------------------------------------------------
            [
                'category' => 'side-shooter-pods',
                'brand' => 'Auxbeam',
                'name' => '4 Inch 36W Side Shooter LED Pod Lights Combo Beam — Pair',
                'sku' => 'ZD000204',
                'short_description' => '4" side shooter pod lights with combo beam for SUV, ATV, UTV, trucks',
                'description' => 'Pair of 4-inch 36W (18W each) side shooter LED pod lights. 3030 chip design. Combo beam pattern. 1,800 LM each. Color temperature: 6000K. IP67 waterproof. Voltage: 9–32V DC. Operating temperature: -40°C to 85°C. Lifespan: 50,000+ hours. Die-cast black aluminum housing. Sold as a pair.',
                'price' => 42.99,
                'compare_price' => 55.99,
                'cost_price' => 22.00,
                'quantity' => 100,
                'weight' => 0.9,
                'is_featured' => false,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'led-pod-lights',
                'brand' => 'Auxbeam',
                'name' => '3 Inch 30W LED Pod Lights Spot Beam — Pair',
                'sku' => 'AB-POD-3-30W',
                'short_description' => 'Compact 3" 30W LED pod lights with spot beam for off-road vehicles',
                'description' => 'Pair of compact 3-inch 30W LED pod lights with focused spot beam for long-range illumination. IP67 waterproof. Die-cast aluminum housing. Voltage: 9–32V. Color temp: 6000K. 50,000hr lifespan. Ideal for rock lights, auxiliary driving lights on trucks, Jeeps, ATVs, and UTVs.',
                'price' => 34.99,
                'compare_price' => 44.99,
                'cost_price' => 18.00,
                'quantity' => 120,
                'weight' => 0.6,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // LED OFF ROAD LIGHTS — Mounting Brackets
            // ---------------------------------------------------------------
            [
                'category' => 'mounting-brackets-accessories',
                'brand' => 'Auxbeam',
                'name' => '1–2 Inch Roll Cage LED Light Bar Mounting Brackets — Pair',
                'sku' => 'QP006297',
                'short_description' => 'Universal roll cage mounting brackets for 1"–2" tubes, compatible with most LED light bars',
                'description' => 'Set of two universal roll cage mounting brackets. Compatible with 1", 1.5", 1.75", and 2" diameter tubes. Aluminum alloy construction with rubber inserts to prevent slipping and scratching. Stainless steel hardware included. Suitable for most LED light bars. Weight: 632g per set.',
                'price' => 28.99,
                'compare_price' => 39.99,
                'cost_price' => 14.00,
                'quantity' => 150,
                'weight' => 0.65,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // SWITCH PANELS — AR Series
            // ---------------------------------------------------------------
            [
                'category' => 'app-control-switch-panels',
                'brand' => 'Auxbeam',
                'name' => 'AR Series 6-Gang Bluetooth LED Switch Panel with APP & Remote Control',
                'sku' => 'QP009889',
                'short_description' => '6-gang switch panel with Bluetooth app, remote control, and 3-mode toggle/momentary/pulsed output',
                'description' => 'AR Series 6-gang LED switch panel with Bluetooth APP control (iOS & Android), wireless remote, and manual toggle. Three output modes per switch: toggle, momentary, and pulsed. RGB backlight with group color settings. Auto-dimming display. IP65 waterproof. Voltage: DC 12V–24V. 1-sided outlet configuration. Includes labeled switch stickers.',
                'price' => 239.99,
                'compare_price' => 299.00,
                'cost_price' => 124.00,
                'quantity' => 30,
                'weight' => 1.2,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'app-control-switch-panels',
                'brand' => 'Auxbeam',
                'name' => 'AR Series 8-Gang Bluetooth LED Switch Panel with APP & Remote Control',
                'sku' => 'QP010785',
                'short_description' => '8-gang switch panel with Bluetooth app, remote control, and 3-mode toggle/momentary/pulsed output',
                'description' => 'AR Series 8-gang LED switch panel with Bluetooth APP control, wireless remote, and manual toggle. Three output modes per switch. RGB backlight. Auto-dimming. IP65 waterproof. Voltage: DC 12V–24V. 1-sided outlet configuration. Ideal for trucks, Jeeps, and off-road vehicles with multiple auxiliary lights.',
                'price' => 269.99,
                'compare_price' => 329.00,
                'cost_price' => 139.00,
                'quantity' => 25,
                'weight' => 1.4,
                'is_featured' => true,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // SWITCH PANELS — KS-80 Knob Series
            // ---------------------------------------------------------------
            [
                'category' => 'knob-switch-panels',
                'brand' => 'Auxbeam',
                'name' => 'KS-80 Knob RGB Switch Panel MAX 120A',
                'sku' => 'QP012186',
                'short_description' => 'Heavy-duty 120A all-solid-state knob switch panel with RGB backlight and 4 external triggers',
                'description' => 'KS-80 all-solid-state load system rated at 120A total output. RGB backlighting with 4 display modes including light dimming and dynamic chase effects. 4 external trigger inputs. Knob control interface for precise adjustment. Voltage: 12V–24V. Compatible with all major switch panel wiring standards. Ideal for high-draw auxiliary light setups.',
                'price' => 299.99,
                'compare_price' => 369.00,
                'cost_price' => 155.00,
                'quantity' => 20,
                'weight' => 1.8,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // RGB LED LIGHTS — Rock Lights
            // ---------------------------------------------------------------
            [
                'category' => 'rgb-rock-lights',
                'brand' => 'Auxbeam',
                'name' => 'RGB LED Rock Light Set with Bluetooth Controller — 4pcs',
                'sku' => 'QP002085',
                'short_description' => '4-piece RGB underglow rock lights with Bluetooth app control — millions of colors',
                'description' => 'Set of 4 RGB LED rock lights with Bluetooth wireless controller. iOS 7+ and Android 4.3+ compatible app. Millions of color options. Die-cast aluminum housing for durability. IP67 waterproof. 120° beam angle. 135.8" (3.45m) power cord per light. Voltage: DC 12–24V. Lifespan: 50,000+ hours.',
                'price' => 62.99,
                'compare_price' => 129.99,
                'cost_price' => 32.00,
                'quantity' => 80,
                'weight' => 0.9,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'rgb-rock-lights',
                'brand' => 'Auxbeam',
                'name' => 'RGB LED Rock Light Set with Bluetooth Controller — 8pcs',
                'sku' => 'QP002314',
                'short_description' => '8-piece RGB underglow rock lights with Bluetooth app control',
                'description' => 'Set of 8 RGB LED rock lights with Bluetooth wireless controller. iOS 7+ and Android 4.3+ compatible app. Millions of color options. Die-cast aluminum housing. IP67 waterproof. 120° beam angle. 135.8" cord per light. DC 12–24V. 50,000+ hour lifespan.',
                'price' => 91.99,
                'compare_price' => 185.99,
                'cost_price' => 47.00,
                'quantity' => 65,
                'weight' => 1.6,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'rgb-rock-lights',
                'brand' => 'Auxbeam',
                'name' => 'RGB LED Rock Light Set with Bluetooth Controller — 12pcs',
                'sku' => 'QP009337',
                'short_description' => '12-piece RGB underglow rock lights with Bluetooth app control',
                'description' => 'Set of 12 RGB LED rock lights with Bluetooth wireless controller. Full truck underglow coverage. iOS 7+ and Android 4.3+ compatible app. Die-cast aluminum housing. IP67 waterproof. DC 12–24V. 50,000+ hour lifespan.',
                'price' => 115.99,
                'compare_price' => 232.99,
                'cost_price' => 60.00,
                'quantity' => 50,
                'weight' => 2.4,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'rgb-rock-lights',
                'brand' => 'Auxbeam',
                'name' => 'Vibrant Series Upgraded RGB LED Rock Lights — Large 4pcs',
                'sku' => 'QP011601',
                'short_description' => 'Next-gen Vibrant Series large RGB rock lights with enhanced brightness and color saturation',
                'description' => 'NEW Vibrant Series rock lights with improved RGB LEDs for brighter and more vivid colors. Larger housing than standard series for wider coverage. Bluetooth app control. IP67 waterproof. DC 12–24V. Sold as a set of 4 large pods.',
                'price' => 109.99,
                'compare_price' => 149.00,
                'cost_price' => 57.00,
                'quantity' => 45,
                'weight' => 1.2,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'rgb-rock-lights',
                'brand' => 'Auxbeam',
                'name' => 'Vibrant Series Upgraded RGB LED Rock Lights — Large 8pcs',
                'sku' => 'QP011600',
                'short_description' => 'Next-gen Vibrant Series large RGB rock lights — 8-piece set',
                'description' => 'NEW Vibrant Series 8-piece rock light set with enhanced RGB LEDs. Brighter and more vivid than the standard series. Bluetooth app control. IP67 waterproof. DC 12–24V. Sold as a set of 8 large pods.',
                'price' => 165.99,
                'compare_price' => 219.00,
                'cost_price' => 86.00,
                'quantity' => 35,
                'weight' => 2.2,
                'is_featured' => false,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // RGB LED LIGHTS — Whip Lights
            // ---------------------------------------------------------------
            [
                'category' => 'rgb-whip-lights',
                'brand' => 'Auxbeam',
                'name' => 'RGB LED Whip Lights 2.8FT with Turn Signal & Brake Light, Bluetooth APP/Remote Control',
                'sku' => 'QP010354',
                'short_description' => '2.8ft RGB whip lights with turn signal, brake light, and wireless control — no mounting brackets',
                'description' => 'RGB LED whip lights (31mm × 850mm) with integrated turn signal and brake light functions. Bluetooth app and wireless remote control. Suitable for off-road vehicles, ATVs, UTVs, and sand rails. IP67 waterproof. Flexible fiberglass whip construction. Multiple RGB modes. Voltage: 12V–24V. Sold as a pair (2 whips).',
                'price' => 189.99,
                'compare_price' => 239.00,
                'cost_price' => 98.00,
                'quantity' => 35,
                'weight' => 1.5,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'rgb-whip-lights',
                'brand' => 'Auxbeam',
                'name' => 'RGB LED Whip Lights 3.8FT with Turn Signal & Brake Light, Bluetooth APP/Remote Control',
                'sku' => 'QP010355',
                'short_description' => '3.8ft RGB whip lights with turn signal, brake light, and wireless control',
                'description' => 'RGB LED whip lights (31mm × 1150mm) with integrated turn signal and brake light functions. Bluetooth app and wireless remote control. IP67 waterproof. Flexible fiberglass construction. Multiple RGB modes. Voltage: 12V–24V. Sold as a pair.',
                'price' => 229.99,
                'compare_price' => 279.00,
                'cost_price' => 119.00,
                'quantity' => 28,
                'weight' => 1.9,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // LED REPLACEMENT BULBS
            // ---------------------------------------------------------------
            [
                'category' => 'h4-9003-bulbs',
                'brand' => 'Auxbeam',
                'name' => 'H4 9003 LED Headlight Bulbs 6000K 10000LM Hi/Lo Beam — Pair',
                'sku' => 'AB-H4-10K',
                'short_description' => 'H4 / 9003 LED headlight bulb conversion — 10,000LM, 6000K cool white, plug-and-play',
                'description' => 'Direct H4 / 9003 LED headlight bulb replacement. 10,000 LM per pair. 6000K cool white. Hi/Lo dual-beam design. 360° adjustable beam angle. Built-in EMC anti-interference. 30-minute quick-cooling fan. Voltage: 9–32V. Rated IP65. Plug-and-play installation. Sold as a pair.',
                'price' => 49.99,
                'compare_price' => 69.99,
                'cost_price' => 26.00,
                'quantity' => 200,
                'weight' => 0.25,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'h7-bulbs',
                'brand' => 'Auxbeam',
                'name' => 'H7 LED Headlight Bulbs 6000K 10000LM — Pair',
                'sku' => 'AB-H7-10K',
                'short_description' => 'H7 LED headlight bulb conversion — 10,000LM, 6000K cool white, plug-and-play',
                'description' => 'Direct H7 LED headlight bulb replacement. 10,000 LM per pair. 6000K cool white. Single-beam design. 360° adjustable beam angle. Built-in EMC. 30-minute quick-cooling fan. Voltage: 9–32V. IP65. Plug-and-play. Sold as a pair.',
                'price' => 49.99,
                'compare_price' => 69.99,
                'cost_price' => 26.00,
                'quantity' => 180,
                'weight' => 0.25,
                'is_featured' => false,
                'is_trending' => true,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'h11-h8-h9-bulbs',
                'brand' => 'Auxbeam',
                'name' => 'H11 H8 H9 LED Headlight Fog Light Bulbs 6000K 6000LM — Pair',
                'sku' => 'AB-H11-6K',
                'short_description' => 'H11/H8/H9 LED bulb replacement for headlights and fog lights — 6000LM, plug-and-play',
                'description' => 'Direct H11/H8/H9 LED replacement bulbs. 6,000 LM per pair. 6000K cool white. Single-beam. Compact design for tight housings. Built-in EMC. IP65. Voltage: 9–32V. Sold as a pair. Compatible with most H11/H8/H9 headlight and fog light housings.',
                'price' => 39.99,
                'compare_price' => 54.99,
                'cost_price' => 21.00,
                'quantity' => 220,
                'weight' => 0.2,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],
            [
                'category' => '9005-hb3-bulbs',
                'brand' => 'Auxbeam',
                'name' => '9005 HB3 LED Headlight Bulbs 6000K 10000LM — Pair',
                'sku' => 'AB-9005-10K',
                'short_description' => '9005/HB3 LED headlight bulb conversion — 10,000LM high beam replacement',
                'description' => 'Direct 9005/HB3 LED headlight replacement bulbs. 10,000 LM per pair. 6000K cool white. Single-beam high beam design. Built-in EMC. 30-minute quick-cooling fan. IP65. Voltage: 9–32V. Sold as a pair.',
                'price' => 49.99,
                'compare_price' => 64.99,
                'cost_price' => 26.00,
                'quantity' => 160,
                'weight' => 0.25,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // WIRING & ACCESSORIES
            // ---------------------------------------------------------------
            [
                'category' => 'wiring-harnesses',
                'brand' => 'Auxbeam',
                'name' => '2-Lead 16AWG LED Light Bar Wiring Harness Kit 12V 40A Relay',
                'sku' => 'ZD000690',
                'short_description' => '2-lead 16AWG wiring harness with 40A relay for dual LED light bars',
                'description' => '2-lead 16AWG wiring harness kit for connecting two LED light bars or pods. Includes 40A relay, 30A fuse holder, rocker switch, and all connectors. 12V compatible. Waterproof connectors. Universal fit. Wire length: approximately 9 feet. Compatible with all Auxbeam light bars.',
                'price' => 27.99,
                'compare_price' => 37.99,
                'cost_price' => 14.00,
                'quantity' => 200,
                'weight' => 0.4,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'wiring-harnesses',
                'brand' => 'Auxbeam',
                'name' => '1-Lead 14AWG LED Light Bar Wiring Harness Kit 300W 12V 40A Relay',
                'sku' => '77721992',
                'short_description' => '1-lead 14AWG heavy-duty wiring harness for single large LED light bars up to 300W',
                'description' => 'Heavy-duty 1-lead 14AWG wiring harness for large single LED light bars up to 300W. Includes 40A relay, 30A fuse holder, rocker switch, and all connectors. 12V compatible. Waterproof connectors. Wire length: approximately 9 feet.',
                'price' => 29.99,
                'compare_price' => 39.99,
                'cost_price' => 15.00,
                'quantity' => 150,
                'weight' => 0.5,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'switch-labels-stickers',
                'brand' => 'Auxbeam',
                'name' => '160 Universal Switch Panel Label Stickers (Horizontal Layout)',
                'sku' => 'QP011252',
                'short_description' => '160 pre-printed icon stickers for customizing switch panel labels — horizontal layout',
                'description' => 'Set of 160 universal icon stickers for labeling switch panel buttons. Horizontal layout. Includes common off-road icons: lights, winch, compressor, fan, horn, and more. Compatible with Auxbeam AR Series switch panels and most aftermarket panels.',
                'price' => 14.99,
                'compare_price' => 19.99,
                'cost_price' => 7.00,
                'quantity' => 300,
                'weight' => 0.05,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],
            [
                'category' => 'extension-cables',
                'brand' => 'Auxbeam',
                'name' => '47 Inch Wiring Harness Extension Cable for 8-Gang Switch Panel',
                'sku' => 'QP007409',
                'short_description' => '47" extension cable for routing 8-gang switch panel wiring through firewall or console',
                'description' => '47-inch (approximately 3.94ft) wiring harness extension cable for 8-gang switch panels. Allows flexible panel placement away from the power source. Weatherproof connectors. Compatible with Auxbeam AR Series 8-gang panels.',
                'price' => 15.99,
                'compare_price' => 21.99,
                'cost_price' => 8.00,
                'quantity' => 250,
                'weight' => 0.15,
                'is_featured' => false,
                'is_trending' => false,
                'shipping_class' => 'standard',
            ],

            // ---------------------------------------------------------------
            // JEEP SPECIFIC — Combo Kits
            // ---------------------------------------------------------------
            [
                'category' => 'jeep-headlights',
                'brand' => 'Auxbeam',
                'name' => 'Jeep Wrangler JK 7 Inch LED Headlights + 4 Inch Fog Lights Combo Kit',
                'sku' => 'AB-JK-COMBO-7-4',
                'short_description' => 'Complete LED headlight and fog light upgrade kit for Jeep Wrangler JK 2007–2017',
                'description' => 'Complete LED lighting upgrade combo for Jeep Wrangler JK (2007–2017). Includes a pair of 7-inch round LED headlights (Hi/Lo beam, DRL) and a pair of 4-inch LED fog lights. Plug-and-play installation. 6000K cool white. IP67 waterproof. Hi beam: 8,000 LM. Fog lights: 2,400 LM each. DOT compliant.',
                'price' => 219.99,
                'compare_price' => 279.99,
                'cost_price' => 114.00,
                'quantity' => 25,
                'weight' => 3.5,
                'is_featured' => true,
                'is_trending' => true,
                'shipping_class' => 'fragile',
            ],
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category'])->first();
            $brand = Brand::where('name', $productData['brand'])->first();
            $shippingClass = ShippingClass::where('slug', $productData['shipping_class'])->first();

            if ($category && $brand) {
                Product::create([
                    'category_id' => $category->id,
                    'brand_id' => $brand->id,
                    'shipping_class_id' => $shippingClass?->id,
                    'name' => $productData['name'],
                    'sku' => $productData['sku'],
                    'short_description' => $productData['short_description'],
                    'description' => $productData['description'],
                    'price' => $productData['price'],
                    'compare_price' => $productData['compare_price'] ?? null,
                    'cost_price' => $productData['cost_price'] ?? null,
                    'quantity' => $productData['quantity'],
                    'low_stock_threshold' => 5,
                    'weight' => $productData['weight'],
                    'weight_unit' => 'kg',
                    'is_featured' => $productData['is_featured'] ?? false,
                    'is_trending' => $productData['is_trending'] ?? false,
                    'status' => 'active',
                    'meta_title' => $productData['name'] . ' | Auxbeam Lighting',
                    'meta_description' => $productData['short_description'],
                ]);
            } else {
                $this->command->warn('Skipped product "' . $productData['name'] . '" — category "' . $productData['category'] . '" or brand "' . $productData['brand'] . '" not found.');
            }
        }

        $this->command->info('Products seeded successfully!');
    }
}
